id: IBAAB231A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T17:39:09+00:00'
last_modified: '2022-06-10T04:11:17.169072+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2397
  title: དཔལ་ཆེན་ཧའོ་དགོན་གྱི་གནས་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9325':
      image_group_id: I3CN2399
      title: Volume 1 of dpal chen ha'o dgon gyi gnas yig
      total_pages: 74
      order: 1
      base_file: 9325.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
